AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for sam

Globals:
  Function:
    Timeout: 60
    CodeUri: .
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512
    Architectures:
      - x86_64

Resources:
  GetCityFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - Statement:
        - Sid: LocationServicesPolicy
          Effect: Allow
          Action:
          - geo:SearchPlaceIndexForPosition
          Resource: !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:place-index/${PlaceIndex}'
      Environment:
        Variables:
          PLACE_INDEX_NAME: !Ref PlaceIndex
    Metadata:
      BuildMethod: makefile

  GetPlacesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - Statement:
        - Sid: LocationServicesPolicy
          Effect: Allow
          Action:
          - geo:SearchPlaceIndexForText
          Resource: !Sub 'arn:aws:geo:${AWS::Region}:${AWS::AccountId}:place-index/${PlaceIndex}'
      Environment:
        Variables:
          PLACE_INDEX_NAME: !Ref PlaceIndex
    Metadata:
      BuildMethod: makefile

  GetWeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              !Ref WeatherApiKeySecret
      Environment:
        Variables:
          API_KEY_SECRET_ARN: !Ref WeatherApiKeySecret
          API_ENDPOINT: 'https://api.airvisual.com/v2/nearest_city'
    Metadata:
      BuildMethod: makefile

  CreateMessageFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile

  WeatherApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: SwiftAPIWeatherApiKeySecret

  PlaceIndex:
    Type: AWS::Location::PlaceIndex
    Properties:
      DataSource: Esri
      IndexName: SwiftAPIPlaceIndex
      PricingPlan: RequestBasedUsage

  GraphQLApi:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Name: SwiftGraphQLApi
      SchemaUri: ./gql/schema.graphql
      Auth:
        Type: API_KEY
      ApiKeys:
        ApiKey: {}
      DataSources:
        Lambda:
          GetCityDataSource:
            FunctionArn: !GetAtt GetCityFunction.Arn
          GetPlacesDataSource:
            FunctionArn: !GetAtt GetPlacesFunction.Arn
          GetWeatherDataSource:
            FunctionArn: !GetAtt GetWeatherFunction.Arn
          CreateMessageDataSource:
            FunctionArn: !GetAtt CreateMessageFunction.Arn
      Functions:
        getCityInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetCityDataSource
          CodeUri: ./gql/invoker.js
        getPlacesInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetPlacesDataSource
          CodeUri: ./gql/invoker.js
        getWeatherInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: GetWeatherDataSource
          CodeUri: ./gql/invoker.js
        createMessageInvoker:
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
          DataSource: CreateMessageDataSource
          CodeUri: ./gql/invoker.js
      Resolvers:
        Query:
          getCity:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - getCityInvoker
          getPlaces:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - getPlacesInvoker
          getWeather:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - getWeatherInvoker
        Mutation:
          createMessage:
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
            Pipeline:
            - createMessageInvoker
Outputs:
  APIEndpointValue:
    Description: AppSync API Endpoint
    Value: !GetAtt GraphQLApi.GraphQLUrl
  ApiKeyValue:
    Description: API Key
    Value: !GetAtt GraphQLApiApiKey.ApiKey
  ApiIdValue:
    Description: API Id
    Value: !GetAtt GraphQLApi.ApiId